// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbox_messages.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeInboxMessage = `-- name: CompleteInboxMessage :execrows
UPDATE inbox_messages
SET completed_at = $3, outcome = $4, transaction_id = $5
WHERE consumer_name = $1 AND message_id = $2 AND completed_at IS NULL
`

type CompleteInboxMessageParams struct {
	ConsumerName  string
	MessageID     string
	CompletedAt   *time.Time
	Outcome       *string
	TransactionID *uuid.UUID
}

func (q *Queries) CompleteInboxMessage(ctx context.Context, arg CompleteInboxMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeInboxMessage,
		arg.ConsumerName,
		arg.MessageID,
		arg.CompletedAt,
		arg.Outcome,
		arg.TransactionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInboxMessage = `-- name: GetInboxMessage :one
SELECT consumer_name, message_id, payload_hash, received_at, completed_at, outcome, transaction_id FROM inbox_messages WHERE consumer_name = $1 AND message_id = $2
`

type GetInboxMessageParams struct {
	ConsumerName string
	MessageID    string
}

func (q *Queries) GetInboxMessage(ctx context.Context, arg GetInboxMessageParams) (InboxMessage, error) {
	row := q.db.QueryRow(ctx, getInboxMessage, arg.ConsumerName, arg.MessageID)
	var i InboxMessage
	err := row.Scan(
		&i.ConsumerName,
		&i.MessageID,
		&i.PayloadHash,
		&i.ReceivedAt,
		&i.CompletedAt,
		&i.Outcome,
		&i.TransactionID,
	)
	return i, err
}

const insertInboxMessage = `-- name: InsertInboxMessage :execrows
INSERT INTO inbox_messages (consumer_name, message_id, payload_hash, received_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (consumer_name, message_id) DO NOTHING
`

type InsertInboxMessageParams struct {
	ConsumerName string
	MessageID    string
	PayloadHash  string
	ReceivedAt   time.Time
}

func (q *Queries) InsertInboxMessage(ctx context.Context, arg InsertInboxMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertInboxMessage,
		arg.ConsumerName,
		arg.MessageID,
		arg.PayloadHash,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
