// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger_postings.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertLedgerPosting = `-- name: InsertLedgerPosting :exec
INSERT INTO ledger_postings (wallet_id, transaction_id, account, direction, amount_minor, currency, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLedgerPostingParams struct {
	WalletID      uuid.UUID
	TransactionID uuid.UUID
	Account       string
	Direction     string
	AmountMinor   int64
	Currency      string
	CreatedAt     time.Time
}

func (q *Queries) InsertLedgerPosting(ctx context.Context, arg InsertLedgerPostingParams) error {
	_, err := q.db.Exec(ctx, insertLedgerPosting,
		arg.WalletID,
		arg.TransactionID,
		arg.Account,
		arg.Direction,
		arg.AmountMinor,
		arg.Currency,
		arg.CreatedAt,
	)
	return err
}

const summarizeWalletPostings = `-- name: SummarizeWalletPostings :one
SELECT
    count(*)::bigint AS postings,
    round(coalesce(sum(CASE WHEN direction = 'CREDIT' THEN amount_minor ELSE -amount_minor END), 0) / 100, 2)::text AS net
FROM ledger_postings
WHERE wallet_id = $1 AND account = 'PLAYER_BALANCES'
`

type SummarizeWalletPostingsRow struct {
	Postings int64
	Net      string
}

func (q *Queries) SummarizeWalletPostings(ctx context.Context, walletID uuid.UUID) (SummarizeWalletPostingsRow, error) {
	row := q.db.QueryRow(ctx, summarizeWalletPostings, walletID)
	var i SummarizeWalletPostingsRow
	err := row.Scan(&i.Postings, &i.Net)
	return i, err
}

const trialBalance = `-- name: TrialBalance :many
SELECT
    currency,
    account,
    count(*)::bigint AS postings,
    round(coalesce(sum(amount_minor) FILTER (WHERE direction = 'DEBIT'), 0) / 100, 2)::text AS debits,
    round(coalesce(sum(amount_minor) FILTER (WHERE direction = 'CREDIT'), 0) / 100, 2)::text AS credits
FROM ledger_postings
GROUP BY currency, account
ORDER BY currency, account
`

type TrialBalanceRow struct {
	Currency string
	Account  string
	Postings int64
	Debits   string
	Credits  string
}

func (q *Queries) TrialBalance(ctx context.Context) ([]TrialBalanceRow, error) {
	rows, err := q.db.Query(ctx, trialBalance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrialBalanceRow{}
	for rows.Next() {
		var i TrialBalanceRow
		if err := rows.Scan(
			&i.Currency,
			&i.Account,
			&i.Postings,
			&i.Debits,
			&i.Credits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
