// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger_entries.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (
    id, wallet_id, transaction_id, direction, amount_minor, currency,
    balance_before_minor, balance_after_minor, wallet_version, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertLedgerEntryParams struct {
	ID                 uuid.UUID
	WalletID           uuid.UUID
	TransactionID      uuid.UUID
	Direction          string
	AmountMinor        int64
	Currency           string
	BalanceBeforeMinor int64
	BalanceAfterMinor  int64
	WalletVersion      int64
	CreatedAt          time.Time
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.ID,
		arg.WalletID,
		arg.TransactionID,
		arg.Direction,
		arg.AmountMinor,
		arg.Currency,
		arg.BalanceBeforeMinor,
		arg.BalanceAfterMinor,
		arg.WalletVersion,
		arg.CreatedAt,
	)
	return err
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, wallet_id, transaction_id, direction, amount_minor, currency, balance_before_minor, balance_after_minor, wallet_version, created_at FROM ledger_entries
WHERE wallet_id = $1 AND wallet_version > $2
ORDER BY wallet_version
LIMIT $3
`

type ListLedgerEntriesParams struct {
	WalletID      uuid.UUID
	WalletVersion int64
	Limit         int32
}

func (q *Queries) ListLedgerEntries(ctx context.Context, arg ListLedgerEntriesParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries, arg.WalletID, arg.WalletVersion, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.WalletID,
			&i.TransactionID,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
			&i.BalanceBeforeMinor,
			&i.BalanceAfterMinor,
			&i.WalletVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
