// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger_entries.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (
    id, wallet_id, transaction_id, direction, amount_minor, currency,
    balance_before_minor, balance_after_minor, wallet_version, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertLedgerEntryParams struct {
	ID                 uuid.UUID
	WalletID           uuid.UUID
	TransactionID      uuid.UUID
	Direction          string
	AmountMinor        int64
	Currency           string
	BalanceBeforeMinor int64
	BalanceAfterMinor  int64
	WalletVersion      int64
	CreatedAt          time.Time
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.ID,
		arg.WalletID,
		arg.TransactionID,
		arg.Direction,
		arg.AmountMinor,
		arg.Currency,
		arg.BalanceBeforeMinor,
		arg.BalanceAfterMinor,
		arg.WalletVersion,
		arg.CreatedAt,
	)
	return err
}
