// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type InboxMessage struct {
	ConsumerName  string
	MessageID     string
	PayloadHash   string
	ReceivedAt    time.Time
	CompletedAt   *time.Time
	Outcome       *string
	TransactionID *uuid.UUID
}

type LedgerEntry struct {
	ID                 uuid.UUID
	WalletID           uuid.UUID
	TransactionID      uuid.UUID
	Direction          string
	AmountMinor        int64
	Currency           string
	BalanceBeforeMinor int64
	BalanceAfterMinor  int64
	WalletVersion      int64
	CreatedAt          time.Time
}

type LedgerPosting struct {
	WalletID      uuid.UUID
	TransactionID uuid.UUID
	Account       string
	Direction     string
	AmountMinor   int64
	Currency      string
	CreatedAt     time.Time
}

type OutboxEvent struct {
	ID            uuid.UUID
	Seq           *int64
	AggregateType string
	AggregateID   uuid.UUID
	PartitionKey  uuid.UUID
	EventType     string
	EventVersion  int32
	CorrelationID string
	CausationID   *string
	Payload       []byte
	OccurredAt    time.Time
	Attempts      int32
	NextAttemptAt time.Time
	ClaimedBy     *string
	ClaimedUntil  *time.Time
	PublishedAt   *time.Time
	LastError     *string
	TraceParent   *string
}

type Provider struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type WagerTransaction struct {
	ID                             uuid.UUID
	Origin                         string
	Kind                           string
	Status                         string
	WalletID                       uuid.UUID
	PlayerID                       uuid.UUID
	Currency                       string
	AmountMinor                    int64
	ProviderID                     *string
	ExternalTransactionID          *string
	IdempotencyKey                 *string
	PayloadHash                    *string
	RoundID                        *string
	GameID                         *string
	ReferenceExternalTransactionID *string
	ReferenceTransactionID         *uuid.UUID
	CorrelationID                  string
	FailureCode                    *string
	ResultBalanceMinor             *int64
	ResultWalletVersion            *int64
	Attempts                       int32
	NextAttemptAt                  *time.Time
	ReferenceDeadlineAt            *time.Time
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
	CompletedAt                    *time.Time
}

type Wallet struct {
	ID           uuid.UUID
	PlayerID     uuid.UUID
	Currency     string
	BalanceMinor int64
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
