// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox_events.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (
    id, aggregate_type, aggregate_id, partition_key, event_type, event_version,
    correlation_id, causation_id, payload, occurred_at, next_attempt_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertOutboxEventParams struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	PartitionKey  uuid.UUID
	EventType     string
	EventVersion  int32
	CorrelationID string
	CausationID   *string
	Payload       []byte
	OccurredAt    time.Time
	NextAttemptAt time.Time
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.PartitionKey,
		arg.EventType,
		arg.EventVersion,
		arg.CorrelationID,
		arg.CausationID,
		arg.Payload,
		arg.OccurredAt,
		arg.NextAttemptAt,
	)
	return err
}
