// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package database

import (
	"context"
)

const providerExists = `-- name: ProviderExists :one
SELECT EXISTS (SELECT 1 FROM providers WHERE id = $1)
`

func (q *Queries) ProviderExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, providerExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
