// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wager_transactions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO wager_transactions (
    id, origin, kind, status, wallet_id, player_id, currency, amount_minor,
    provider_id, external_transaction_id, idempotency_key, payload_hash, round_id, game_id,
    reference_external_transaction_id, reference_transaction_id, correlation_id, failure_code,
    result_balance_minor, result_wallet_version, attempts, next_attempt_at, reference_deadline_at,
    created_at, updated_at, completed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21, $22, $23,
    $24, $25, $26
)
`

type InsertTransactionParams struct {
	ID                             uuid.UUID
	Origin                         string
	Kind                           string
	Status                         string
	WalletID                       uuid.UUID
	PlayerID                       uuid.UUID
	Currency                       string
	AmountMinor                    int64
	ProviderID                     *string
	ExternalTransactionID          *string
	IdempotencyKey                 *string
	PayloadHash                    *string
	RoundID                        *string
	GameID                         *string
	ReferenceExternalTransactionID *string
	ReferenceTransactionID         *uuid.UUID
	CorrelationID                  string
	FailureCode                    *string
	ResultBalanceMinor             *int64
	ResultWalletVersion            *int64
	Attempts                       int32
	NextAttemptAt                  *time.Time
	ReferenceDeadlineAt            *time.Time
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
	CompletedAt                    *time.Time
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.ID,
		arg.Origin,
		arg.Kind,
		arg.Status,
		arg.WalletID,
		arg.PlayerID,
		arg.Currency,
		arg.AmountMinor,
		arg.ProviderID,
		arg.ExternalTransactionID,
		arg.IdempotencyKey,
		arg.PayloadHash,
		arg.RoundID,
		arg.GameID,
		arg.ReferenceExternalTransactionID,
		arg.ReferenceTransactionID,
		arg.CorrelationID,
		arg.FailureCode,
		arg.ResultBalanceMinor,
		arg.ResultWalletVersion,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.ReferenceDeadlineAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.CompletedAt,
	)
	return err
}
