// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getWallet = `-- name: GetWallet :one
SELECT id, player_id, currency, balance_minor, version, created_at, updated_at FROM wallets WHERE id = $1
`

func (q *Queries) GetWallet(ctx context.Context, id uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWallet, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Currency,
		&i.BalanceMinor,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletForUpdate = `-- name: GetWalletForUpdate :one
SELECT id, player_id, currency, balance_minor, version, created_at, updated_at FROM wallets WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetWalletForUpdate(ctx context.Context, id uuid.UUID) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletForUpdate, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Currency,
		&i.BalanceMinor,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWallet = `-- name: InsertWallet :exec
INSERT INTO wallets (id, player_id, currency, balance_minor, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertWalletParams struct {
	ID           uuid.UUID
	PlayerID     uuid.UUID
	Currency     string
	BalanceMinor int64
	Version      int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) InsertWallet(ctx context.Context, arg InsertWalletParams) error {
	_, err := q.db.Exec(ctx, insertWallet,
		arg.ID,
		arg.PlayerID,
		arg.Currency,
		arg.BalanceMinor,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :execrows
UPDATE wallets
SET balance_minor = $3, version = version + 1, updated_at = $4
WHERE id = $1 AND version = $2
`

type UpdateWalletBalanceParams struct {
	ID           uuid.UUID
	Version      int64
	BalanceMinor int64
	UpdatedAt    time.Time
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWalletBalance,
		arg.ID,
		arg.Version,
		arg.BalanceMinor,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
